#!/usr/bin/tcsh 
#section 1
#set echo
set cutfl = "c1-4 --complement"
#section 1.5
if ( "$PWD" =~ */buttonRoom/.nw/u/se/d/nw/nw/s/s/s && $1 == "n" && ! -f ~/_/i/i/preserver ) then
    echo You dive in the water, and at first notice it is quite cold. \ You then
    echo start to get used to it as you realize that you never really learned how
    echo to swim.
    echo 
    echo You are dead.
    touch ~/_/die
    exit 1
endif

#Section #2 (It is the same as PA3):
if ( -d $1 ) then
   #It is the locked door. It needs to get a second chance, in PA3.sh.
   echo You must type a 3 digit combination code to enter this room.
   echo -n "Enter it here: "
   set X = $<:q
   if ( x$X == x418 ) then
      chmod 766 w
      cd w
      if ( ! -e ~/_/i/i/lamp ) then
         grep ~/PA3/expl*Walkthrough.txt -elikely|cut -$cutfl|tee ~/_/grue de*
	 exit 1
      endif
   else
      echo Sorry, that combination is incorrect.&& exit 0
   endif

#Section #3 (It is the same as PA3):
else if ( ( -e $1 ) || ( -l $1 ) ) then
   echo You cannot go that way. && exit 0
else
   basename `pwd`|tr sundew ndsuwe | xargs expr $1 \!= >&~/X && echo You cannot go that way. && exit 0
   cd ..
endif

#section 3.5
if ( ! -e lamp && ! -e ~/_/i/i/lamp && "$PWD" !~ */receivingRoom/e && "$PWD" !~ */receivingRoom/e/. && "$PWD" !~ */receivingRoom && "$PWD" !~ */nw/s/* ) then 
   #echo cantmove 3.5
   #pwd
   grep ~/PA1/explana*Walkthrough.txt -elikely|cut -$cutfl|tee ~/_/grue > de*
endif
if ( -e w/cable ) chmod 400 w

#Section #4 (It is the same as PA3):
head -n `ls [19]` de*&&mv 9 1 >&~/X
grep -hw `ls -d *| paste ~/_/es -` -h ~/_/T*|cut -d\; -f1
exit 3