#!/usr/bin/tcsh 
#set echo
set cutfl = "c1-4 --complement"

ls | grep -w $1 >&~/X
set temp = $status 
if ( $1 == 'w' && "$PWD" =~ */mistyRoom/e/e/n ) then
    echo "You must type a 3 digit combination code to enter this room."
    echo -n "Enter it here: "
    set cb = $<
    tr "a-zA-Z" "n-za-mN-ZA-M" <~/PA3/savedgame> test.enc
    set ans = `grep "combination" test.enc | cut -d '"' -f 2`
    if ( $cb == $ans ) then
    chmod 755 w
    cd w
        if ( -f ~/_/i/i/lamp == 0 ) then
            grep ~/PA3/expl*Walkthrough.txt -elikely|cut -$cutfl|tee de*
            exit 1
        endif
    else
        echo "Sorry, that combination is incorrect." && exit 0
    endif
else if ( $temp == 0 ) then
    echo "You cannot go that way." && exit 0
else
    basename `pwd` | tr "newsud" "swendu" | grep -w $1 >& /dev/null|| echo -n "" && echo "You cannot go that way." && exit 0
    cd ..
endif
head -n `ls [19]` de* && mv 9 1 >&~/X
grep -hw `ls -d * | paste ~/_/es -` -h ~/_/T*|cut -d\; -f1
exit 3
